services:

  frontend:
    build:
      context: ./frontend
    container_name: devops-roadmap-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build:
      context: ./backend
    container_name: devops-roadmap-backend
    expose:
      - "3000"
    restart: unless-stopped
