services:

  mysql:
    image: mysql:8.4
    container_name: devops-roadmap-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ChangeThisRootPassword123!
      MYSQL_DATABASE: devops_roadmap
      MYSQL_USER: devops
      MYSQL_PASSWORD: ChangeThisDBPassword123!
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped


  backend:
    build:
      context: ./backend
    container_name: devops-roadmap-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: devops_roadmap
      DB_USER: devops
      DB_PASSWORD: ChangeThisDBPassword123!
      ADMIN_USER: admin
      ADMIN_PASSWORD: ChangeThisAdminPassword123!
      JWT_SECRET: ChangeThisJWTSecretToARandomLongValue123456789
    expose:
      - "3000"
    depends_on:
      - mysql
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
    container_name: devops-roadmap-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped


volumes:

  mysql-data:
